### ISSUE TITLE
version

### ISSUE THREAD

**Issue by robotdragonfirex** [horionclient/Injector#10]
please make it compatible with 1.19.30 it crashes when i try to load it

**Comment by robotdragonfirex** [comment]
for now i cant use it

**Comment by robotdragonfirex** [comment]
for now i cant use this

**Comment by robotdragonfirex** [comment]
e

**Comment by robotdragonfirex** [comment]
it crashes when i open the loader and inject it

**Comment by richardletshacks** [comment]
This repository is for the Injector, not the mod itself. Please refrain from creating a new issue regarding the mod.

**Comment by robotdragonfirex** [comment]
ok
